name: "Deploy app release"

on:
  push:
    branches: [ "master" ]

env:
  SOLUTION_FILE: ExcelCombinator.sln
  RELEASE_FOLDER: ExcelCombinator\bin\Release
  
jobs:
  compile_and_publish:
    runs-on: windows-2019
    env:
      MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\
      
    steps:
      - name: Get current date # get the date of the build
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
      - name: Checkout Git Project
        uses: actions/checkout@v2
        
      - name: Use Nuget
        uses: nuget/setup-nuget@v1

      - name: Restore nuget packages
        run: nuget restore ${{ env.SOLUTION_FILE }}

      - name: Compile Solution
        shell: cmd
        run: '"%MSBUILD_PATH%\MSBuild.exe" ${{ env.SOLUTION_FILE }} /p:Configuration=Release'

      - name: Remove pdb and xml files
        run: |
          rm .\${{ env.RELEASE_FOLDER }}\*.pdb
          rm .\${{ env.RELEASE_FOLDER }}\*.xml
        
      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with: 
          name: ExcelCombinator_${{ steps.date.outputs.date }}
          path: ${{ env.RELEASE_FOLDER }}
          retention-days: 5
          
      - name: zip release artifact
        shell: pwsh
        run: Compress-Archive -Path .\${{ env.RELEASE_FOLDER }}\* -DestinationPath ExcelCombinator_${{ steps.date.outputs.date }}.zip
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.date }}
          release_name: Release ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ExcelCombinator_${{ steps.date.outputs.date }}.zip
          asset_name: ExcelCombinator_${{ steps.date.outputs.date }}.zip
          asset_content_type: application/zip
