name: "Deploy app"

on:
  push:
    branches: [ "master" ]

env:
  SOLUTION_FILE: ExcelCombinator.sln
  RELEASE_FOLDER: WpfApp1\bin\Release
  
jobs:
  compile:
    runs-on: windows-2019
    env:
      MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\
      
    steps:
      - name: Get current date # get the date of the build
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
      - name: Checkout Git Project
        uses: actions/checkout@v2
        
      - name: Use Nuget
        uses: nuget/setup-nuget@v1

      - name: Restore nuget packages
        run: nuget restore ${{ env.SOLUTION_FILE }}

      - name: Compile Solution
        shell: cmd
        run: '"%MSBUILD_PATH%\MSBuild.exe" ${{ env.SOLUTION_FILE }} /p:Configuration=Release'

      - name: Remove pdb and xml files
        run: |
          rm .\${{ env.RELEASE_FOLDER }}\*.pdb
          rm .\${{ env.RELEASE_FOLDER }}\*.xml
          
      - name: zip win artifact
        shell: pwsh
        run: Compress-Archive -Path .\${{ env.RELEASE_FOLDER }} -DestinationPath ExcelCombinator_${{ steps.date.outputs.date }}.zip
        
      - name: list
        run: dir
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.date }}
          release_name: Release ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
