name: "Deploy app"

on:
  push:
    branches: [ "master" ]

env:
  SOLUTION_FILE: ExcelCombinator.sln
  RELEASE_FOLDER: WpfApp1\bin\Release
  
jobs:
  compile:
    runs-on: windows-2019
    env:
      MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\
      
    steps:
      - name: Checkout Git Project
        uses: actions/checkout@v2
        
      - name: List
        run: dir

      - name: Compile Solution
        shell: cmd
        run: '"%MSBUILD_PATH%\MSBuild.exe" ${{ env.SOLUTION_FILE }} /p:Configuration=Release'

      - name: Remove pdb and xml files
        run: |
          rm .\${{ env.RELEASE_FOLDER }}\*.pdb
          rm .\${{ env.RELEASE_FOLDER }}\*.xml
          
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: "${{ env.RELEASE_FOLDER }}"
